import { useState, useCallback } from 'react';
import { ScrollView, View, Text, StyleSheet, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useFocusEffect, router, useLocalSearchParams } from 'expo-router';
import { colors, fonts, radius, spacing } from '../../theme/brand';
import { IconCalendar, IconQR, IconClock, IconPin, IconReceipt, IconStar } from '../../components/Icons';
import { qrApi, api, wellnessApi } from '../../lib/api';
import { openDirections } from '../../lib/directions';

type GymBooking = {
  id?: string;
  _id?: string;
  slotDate?: string;
  status?: string;
  bookingRef?: string;
  manualCode?: string;
  bookedAt?: string;
  createdAt?: string;
  isAutoGenerated?: boolean;
  slot?: { date?: string; startTime?: string; endTime?: string };
  sessionType?: { name?: string; color?: string; kind?: string };
  gym?: { id?: string; name?: string };
  gymId?: string;
  gymName?: string;
  subscription?: { planType?: string; startDate?: string; endDate?: string };
};

function toList(res: any) {
  if (Array.isArray(res)) return res;
  return res?.bookings || res?.data || [];
}

function formatDate(value?: string) {
  if (!value) return '-';
  const source = /^\d{4}-\d{2}-\d{2}$/.test(value) ? `${value}T12:00:00` : value;
  const d = new Date(source);
  if (Number.isNaN(d.getTime())) return '-';
  return d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' });
}

function formatTime(value?: string) {
  if (!value) return '-';
  if (/^\d{1,2}:\d{2}/.test(value)) {
    const [hourRaw, minuteRaw] = value.split(':');
    const hour = Number(hourRaw);
    const minute = Number(minuteRaw);
    if (Number.isFinite(hour) && Number.isFinite(minute)) {
      const suffix = hour >= 12 ? 'PM' : 'AM';
      const hour12 = hour % 12 || 12;
      return `${hour12}:${String(minute).padStart(2, '0')} ${suffix}`;
    }
  }
  const d = new Date(value);
  if (Number.isNaN(d.getTime())) return '-';
  return d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true });
}

function formatTimeRange(start?: string, end?: string) {
  if (!start && !end) return '-';
  if (!end) return formatTime(start);
  return `${formatTime(start)} - ${formatTime(end)}`;
}

function getBookingId(booking: GymBooking) {
  return String(booking.id || booking._id || '');
}

function getBookingDate(booking: GymBooking) {
  return booking.slot?.date || booking.slotDate || booking.bookedAt || booking.createdAt || '';
}

function getStatusLabel(status?: string) {
  const clean = String(status || 'confirmed').replace(/_/g, ' ');
  return clean.charAt(0).toUpperCase() + clean.slice(1);
}

function todayISTValue() {
  return new Date(Date.now() + 5.5 * 3600 * 1000).toISOString().split('T')[0];
}

function dateValue(value?: string) {
  return String(value || '').slice(0, 10);
}

const STATUS_COLORS: Record<string, string> = {
  confirmed: colors.accent,
  pending: '#ffb400',
  attended: '#00D4FF',
  not_attended: '#ff6b6b',
  cancelled: '#ff5a5a',
  completed: colors.t2,
};

export default function BookingsTab() {
  const params = useLocalSearchParams<{ bookingCreated?: string; bookingRef?: string; gymName?: string; gymLat?: string; gymLng?: string; gymAddress?: string }>();
  const [activeTab, setActiveTab] = useState<'gym' | 'wellness'>('gym');
  const [gymBookings, setGymBookings] = useState<GymBooking[]>([]);
  const [activeBooking, setActiveBooking] = useState<any>(null);
  const [wellnessBookings, setWellnessBookings] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [wellnessLoading, setWellnessLoading] = useState(false);

  async function loadGymBookings() {
    const [bookingsResult, activeResult] = await Promise.allSettled([
      api.get('/sessions/my-bookings'),
      qrApi.getActiveBooking(),
    ]);

    if (bookingsResult.status === 'fulfilled') {
      setGymBookings(toList(bookingsResult.value));
    } else {
      setGymBookings([]);
    }

    if (
      activeResult.status === 'fulfilled' &&
      activeResult.value?.active &&
      activeResult.value?.bookingQr
    ) {
      setActiveBooking(activeResult.value.bookingQr);
    } else {
      setActiveBooking(null);
    }
  }

  function loadWellnessBookings() {
    setWellnessLoading(true);
    return wellnessApi.myBookings()
      .then((res: any) => setWellnessBookings(toList(res)))
      .catch(() => setWellnessBookings([]))
      .finally(() => setWellnessLoading(false));
  }

  useFocusEffect(useCallback(() => {
    setLoading(true);
    Promise.all([loadGymBookings(), loadWellnessBookings()])
      .finally(() => setLoading(false));
  }, []));

  function openQr() {
    if (!activeBooking?.token) return;
    router.push({
      pathname: '/qr',
      params: {
        token: activeBooking.token,
        expiresAt: activeBooking.expiresAt,
        bookedAt: activeBooking.bookedAt,
        gymId: activeBooking.gymId || '',
        gymName: activeBooking.gymName || '',
        bookingId: activeBooking.bookingId || '',
        bookingRef: activeBooking.bookingRef || '',
        manualCode: activeBooking.manualCode || activeBooking.bookingRef || activeBooking.bookingId || '',
      },
    });
  }

  function isActiveQrBooking(booking: GymBooking) {
    const bookingId = getBookingId(booking);
    const activeId = String(activeBooking?.bookingId || '');
    const activeRef = String(activeBooking?.bookingRef || activeBooking?.manualCode || '');
    const bookingRef = String(booking.bookingRef || booking.manualCode || '');
    return !!activeBooking?.token && (
      (!!bookingId && bookingId === activeId) ||
      (!!bookingRef && bookingRef === activeRef)
    );
  }

  function handleCancelGym(booking: GymBooking) {
    const bookingId = getBookingId(booking);
    if (!bookingId) return;
    Alert.alert('Cancel Booking', 'Are you sure? This cannot be undone.', [
      { text: 'No', style: 'cancel' },
      {
        text: 'Yes, Cancel', style: 'destructive',
        onPress: async () => {
          try {
            await api.post(`/sessions/cancel/${bookingId}`, {});
            await loadGymBookings();
            Alert.alert('Cancelled', 'Your booking has been cancelled.');
          } catch (err: any) {
            Alert.alert('Error', err?.message || 'Could not cancel booking.');
          }
        },
      },
    ]);
  }

  function canRescheduleDayPass(booking: GymBooking, status: string) {
    const normalized = String(status || '').toLowerCase();
    if (normalized !== 'cancelled' && normalized !== 'not_attended' && normalized !== 'missed') return false;
    if (booking.subscription?.planType !== 'day_pass') return false;
    const validUntil = dateValue(booking.subscription?.endDate || booking.slotDate);
    return !!(booking.gym?.id || booking.gymId) && validUntil >= todayISTValue();
  }

  function handleRescheduleGym(booking: GymBooking) {
    const targetGymId = booking.gym?.id || booking.gymId;
    if (!targetGymId) return;
    router.push({ pathname: '/slots', params: { gymId: targetGymId } } as any);
  }

  async function handleViewInvoice(bookingId: string) {
    try {
      const inv: any = await wellnessApi.invoice(bookingId);
      Alert.alert(
        `Invoice ${inv.invoiceNumber}`,
        `Service: ${inv.service?.name || '-'}\n` +
        `Provider: ${inv.partner?.name || '-'}\n` +
        `Date: ${formatDate(inv.bookingDate)}\n` +
        `Amount: Rs ${Number(inv.amount).toLocaleString()}\n` +
        `Status: ${inv.status}`,
        [{ text: 'OK' }],
      );
    } catch {
      Alert.alert('Invoice', 'Could not load invoice. Please try again.');
    }
  }

  function handleRateWellness(booking: any) {
    const partnerId = booking.partner?.id || booking.partnerId;
    if (!partnerId) {
      Alert.alert('Review unavailable', 'This booking is not linked to a wellness partner.');
      return;
    }
    router.push({
      pathname: '/review',
      params: {
        wellnessPartnerId: partnerId,
        wellnessPartnerName: booking.partner?.name || 'Wellness Partner',
        wellnessImage: booking.partner?.photos?.[0] || '',
      },
    } as any);
  }

  const secsLeft = activeBooking
    ? Math.max(0, Math.floor((new Date(activeBooking.expiresAt).getTime() - Date.now()) / 1000))
    : 0;
  const hrs = Math.floor(secsLeft / 3600);
  const mins = Math.floor((secsLeft % 3600) / 60);
  const showBookingCreated = activeTab === 'gym' && params.bookingCreated === '1';

  return (
    <SafeAreaView style={s.root} edges={['top', 'left', 'right']}>
      <View style={s.headerRow}>
        <Text style={s.pageTitle}>My Bookings</Text>
      </View>

      <View style={s.tabRow}>
        {(['gym', 'wellness'] as const).map(tab => (
          <TouchableOpacity
            key={tab}
            style={[s.tab, activeTab === tab && s.tabActive]}
            onPress={() => setActiveTab(tab)}
          >
            <Text style={[s.tabText, activeTab === tab && s.tabTextActive]}>
              {tab === 'gym' ? 'Gym Sessions' : 'Wellness'}
            </Text>
          </TouchableOpacity>
        ))}
      </View>

      <ScrollView contentContainerStyle={s.container} showsVerticalScrollIndicator={false}>
        {loading ? (
          <View style={s.centre}><ActivityIndicator color={colors.accent} /></View>
        ) : activeTab === 'gym' ? (
          <View style={s.list}>
            {showBookingCreated ? (
              <View style={s.confirmCard}>
                <View style={s.activeTop}>
                  <View style={s.statusDot} />
                  <Text style={s.statusText}>Booking Confirmed</Text>
                </View>
                <Text style={s.confirmTitle}>{params.gymName || 'Your gym slot is booked'}</Text>
                <Text style={s.confirmText}>
                  Your slot is listed below. The QR will appear when check-in opens for the booked time.
                </Text>
                {params.bookingRef ? <Text style={s.confirmRef}>#{params.bookingRef}</Text> : null}
                <TouchableOpacity
                  style={s.directionsBtn}
                  activeOpacity={0.85}
                  onPress={() => openDirections({
                    lat: params.gymLat ? Number(params.gymLat) : null,
                    lng: params.gymLng ? Number(params.gymLng) : null,
                    name: params.gymName,
                    address: params.gymAddress,
                  })}
                >
                  <IconPin size={15} color="#060606" />
                  <Text style={s.directionsBtnText}>Get Directions</Text>
                </TouchableOpacity>
              </View>
            ) : null}

            {activeBooking ? (
              <View style={s.activeCard}>
                <View style={s.activeTop}>
                  <View style={s.statusDot} />
                  <Text style={s.statusText}>Active Session</Text>
                </View>
                <Text style={s.gymNameText}>{activeBooking.gymName || 'Booked Gym'}</Text>
                <View style={s.metaRow}>
                  <IconCalendar size={13} color={colors.t2} />
                  <Text style={s.metaText}>{formatDate(activeBooking.bookedAt)} | {formatTime(activeBooking.bookedAt)}</Text>
                </View>
                {secsLeft > 0 && (
                  <View style={s.timerRow}>
                    <IconClock size={13} color={colors.accent} />
                    <Text style={s.timerText}>{hrs > 0 ? `${hrs}h ${mins}m` : `${mins}m`} remaining</Text>
                  </View>
                )}
                <View style={s.qrBtnRow}>
                  <TouchableOpacity style={s.qrBtn} onPress={openQr} activeOpacity={0.86}>
                    <IconQR size={16} color="#060606" />
                    <Text style={s.qrBtnText}>Show QR</Text>
                  </TouchableOpacity>
                </View>
              </View>
            ) : null}

            {gymBookings.length === 0 ? (
              <View style={s.empty}>
                <View style={s.emptyIcon}><IconCalendar size={32} color={colors.t2} /></View>
                <Text style={s.emptyTitle}>No Gym Sessions</Text>
                <Text style={s.emptySub}>Book a gym slot to see your session history here.</Text>
                <TouchableOpacity style={s.browseBtn} onPress={() => router.push('/gyms' as any)}>
                  <Text style={s.browseBtnText}>Browse Gyms</Text>
                </TouchableOpacity>
              </View>
            ) : (
              <>
                <Text style={s.sectionTitle}>Session History</Text>
                {gymBookings.map((booking) => {
                  const bookingId = getBookingId(booking);
                  const status = String(booking.status || 'confirmed').toLowerCase();
                  const statusColor = STATUS_COLORS[status] || colors.t2;
                  const sessionColor = booking.sessionType?.color || colors.accent;
                  const gymName = booking.gym?.name || booking.gymName || 'Gym';
                  const sessionName = booking.sessionType?.name || 'Gym Workout';
                  const date = formatDate(getBookingDate(booking));
                  const time = formatTimeRange(booking.slot?.startTime, booking.slot?.endTime);
                  const canCancel = status === 'confirmed';
                  const canShowQr = isActiveQrBooking(booking);
                  const canReschedule = canRescheduleDayPass(booking, status);

                  return (
                    <View key={bookingId || `${gymName}-${booking.bookedAt}`} style={[s.bookingCard, { borderColor: `${sessionColor}30` }]}>
                      <View style={s.bookingTop}>
                        <View style={[s.typeDot, { backgroundColor: sessionColor }]} />
                        <Text style={[s.sessionName, { color: sessionColor }]} numberOfLines={1}>{sessionName}</Text>
                        <View style={[s.statusBadge, { borderColor: statusColor + '50', backgroundColor: statusColor + '15' }]}>
                          <Text style={[s.statusBadgeText, { color: statusColor }]}>{getStatusLabel(status)}</Text>
                        </View>
                      </View>

                      <Text style={s.bookingGymName}>{gymName}</Text>
                      <View style={s.bookingMeta}>
                        <View style={s.metaRow}>
                          <IconCalendar size={12} color={colors.t2} />
                          <Text style={s.metaText}>{date}</Text>
                        </View>
                        <View style={s.metaRow}>
                          <IconClock size={12} color={colors.t2} />
                          <Text style={s.metaText}>{time}</Text>
                        </View>
                      </View>

                      <View style={s.bookingFooter}>
                        <Text style={s.bookingRef}>{booking.bookingRef ? `#${booking.bookingRef}` : 'Booked'}</Text>
                        <View style={s.bookingActions}>
                          <TouchableOpacity
                            style={s.directionsGhost}
                            onPress={() => openDirections({ name: gymName, address: (booking as any).gym?.address })}
                          >
                            <IconPin size={13} color={colors.accent} />
                            <Text style={s.directionsGhostText}>Directions</Text>
                          </TouchableOpacity>
                          {canShowQr ? (
                            <TouchableOpacity style={s.smallQrBtn} onPress={openQr}>
                              <IconQR size={13} color="#060606" />
                              <Text style={s.smallQrBtnText}>QR</Text>
                            </TouchableOpacity>
                          ) : null}
                          {canCancel ? (
                            <TouchableOpacity style={s.cancelBtn} onPress={() => handleCancelGym(booking)}>
                              <Text style={s.cancelBtnText}>Cancel</Text>
                            </TouchableOpacity>
                          ) : null}
                          {canReschedule ? (
                            <TouchableOpacity style={s.rescheduleBtn} onPress={() => handleRescheduleGym(booking)}>
                              <Text style={s.rescheduleBtnText}>Choose New Time</Text>
                            </TouchableOpacity>
                          ) : null}
                        </View>
                      </View>
                    </View>
                  );
                })}
              </>
            )}
          </View>
        ) : (
          wellnessLoading ? (
            <View style={s.centre}><ActivityIndicator color={colors.accent} /></View>
          ) : wellnessBookings.length === 0 ? (
            <View style={s.empty}>
              <View style={s.emptyIcon}><IconPin size={32} color={colors.t2} /></View>
              <Text style={s.emptyTitle}>No Wellness Bookings</Text>
              <Text style={s.emptySub}>Book a spa session or home service to see it here.</Text>
              <TouchableOpacity style={s.browseBtn} onPress={() => router.push('/wellness' as any)}>
                <Text style={s.browseBtnText}>Explore Wellness</Text>
              </TouchableOpacity>
            </View>
          ) : (
            <View style={{ gap: 12 }}>
              {wellnessBookings.map((b) => {
                const status = String(b.status || 'pending').toLowerCase();
                const statusColor = STATUS_COLORS[status] || colors.t2;
                const canRate = ['confirmed', 'completed', 'paid'].includes(status) && !!(b.partner?.id || b.partnerId);
                return (
                  <View key={b.id} style={s.wellnessCard}>
                    <View style={s.wellnessCardTop}>
                      <View style={{ flex: 1 }}>
                        <Text style={s.wellnessServiceName}>{b.service?.name || 'Wellness Service'}</Text>
                        <Text style={s.wellnessPartnerName}>{b.partner?.name || ''}</Text>
                      </View>
                      <View style={[s.statusBadge, { borderColor: statusColor + '50', backgroundColor: statusColor + '15' }]}>
                        <Text style={[s.statusBadgeText, { color: statusColor }]}>
                          {getStatusLabel(status)}
                        </Text>
                      </View>
                    </View>

                    <View style={s.wellnessMeta}>
                      <View style={s.metaRow}>
                        <IconCalendar size={12} color={colors.t2} />
                        <Text style={s.metaText}>{formatDate(b.bookingDate)} | {formatTime(b.bookingDate)}</Text>
                      </View>
                      {b.service?.durationMinutes ? (
                        <View style={s.metaRow}>
                          <IconClock size={12} color={colors.t2} />
                          <Text style={s.metaText}>{b.service.durationMinutes} min</Text>
                        </View>
                      ) : null}
                    </View>

                    <View style={s.wellnessFooter}>
                      <Text style={s.wellnessAmount}>Rs {Number(b.amount || 0).toLocaleString()}</Text>
                      <View style={s.wellnessActions}>
                        {canRate ? (
                          <TouchableOpacity style={s.rateBtn} onPress={() => handleRateWellness(b)}>
                            <IconStar size={13} color="#060606" />
                            <Text style={s.rateBtnText}>Rate</Text>
                          </TouchableOpacity>
                        ) : null}
                        <TouchableOpacity
                          style={s.invoiceBtn}
                          onPress={() => handleViewInvoice(b.id)}
                        >
                          <IconReceipt size={13} color={colors.accent} />
                          <Text style={s.invoiceBtnText}>Invoice</Text>
                        </TouchableOpacity>
                      </View>
                    </View>
                  </View>
                );
              })}
            </View>
          )
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  headerRow: { paddingHorizontal: spacing.lg, paddingTop: 8, paddingBottom: 4 },
  pageTitle: { fontFamily: fonts.serif, fontSize: 26, color: '#fff' },

  tabRow: {
    flexDirection: 'row', marginHorizontal: spacing.lg, marginVertical: 14,
    backgroundColor: colors.surface, borderRadius: radius.xl, padding: 4,
    borderWidth: 1, borderColor: colors.border,
  },
  tab: {
    flex: 1, paddingVertical: 9, alignItems: 'center', borderRadius: radius.lg,
  },
  tabActive: { backgroundColor: colors.accentSoft },
  tabText: { fontFamily: fonts.sansMedium ?? fonts.sans, fontSize: 13, color: colors.t2 },
  tabTextActive: { fontFamily: fonts.sansBold, color: colors.accent },

  container: { paddingHorizontal: spacing.lg, paddingBottom: 16 },
  centre: { paddingTop: 60, alignItems: 'center' },
  list: { gap: 12 },
  sectionTitle: { fontFamily: fonts.serif, fontSize: 17, color: '#fff', marginTop: 4 },
  activeCard: {
    backgroundColor: 'rgba(0,212,106,0.06)', borderRadius: radius.xl,
    borderWidth: 1, borderColor: 'rgba(0,212,106,0.25)', padding: 20, gap: 10,
  },
  activeTop: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accent },
  statusText: { fontFamily: fonts.sansBold, fontSize: 11, color: colors.accent, letterSpacing: 1, textTransform: 'uppercase' },
  gymNameText: { fontFamily: fonts.sansBold, fontSize: 22, color: '#fff' },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  metaText: { fontFamily: fonts.sans, fontSize: 13, color: colors.t2 },
  timerRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  timerText: { fontFamily: fonts.sansBold, fontSize: 14, color: colors.accent },
  qrBtnRow: { marginTop: 4 },
  qrBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    backgroundColor: colors.accent, borderRadius: radius.pill,
    alignSelf: 'flex-start', paddingHorizontal: 20, paddingVertical: 10,
  },
  qrBtnText: { fontFamily: fonts.sansBold, fontSize: 13, color: '#060606' },
  confirmCard: {
    backgroundColor: 'rgba(204,255,0,0.08)',
    borderRadius: radius.xl,
    borderWidth: 1,
    borderColor: colors.accentBorder,
    padding: 18,
    gap: 8,
  },
  confirmTitle: { fontFamily: fonts.sansBold, fontSize: 18, color: '#fff' },
  confirmText: { fontFamily: fonts.sans, fontSize: 13, color: colors.t2, lineHeight: 19 },
  confirmRef: { fontFamily: fonts.sansBold, fontSize: 12, color: colors.accent, letterSpacing: 1.2 },
  directionsBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 7,
    backgroundColor: colors.accent, borderRadius: radius.pill,
    alignSelf: 'flex-start', paddingHorizontal: 16, paddingVertical: 9, marginTop: 4,
  },
  directionsBtnText: { fontFamily: fonts.sansBold, fontSize: 12, color: '#060606' },
  directionsGhost: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    borderWidth: 1, borderColor: colors.accentBorder, borderRadius: radius.pill,
    paddingHorizontal: 12, paddingVertical: 7,
  },
  directionsGhostText: { fontFamily: fonts.sansBold, fontSize: 12, color: colors.accent },

  bookingCard: {
    backgroundColor: colors.glass, borderRadius: radius.xl,
    borderWidth: 1, borderColor: colors.borderGlass, padding: 16, gap: 10,
  },
  bookingTop: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  typeDot: { width: 10, height: 10, borderRadius: 5 },
  sessionName: { fontFamily: fonts.sansBold, fontSize: 13, flex: 1 },
  bookingGymName: { fontFamily: fonts.sansBold, fontSize: 17, color: '#fff' },
  bookingMeta: { gap: 5 },
  bookingFooter: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10,
  },
  bookingRef: { fontFamily: fonts.sansBold, fontSize: 12, color: colors.accent, letterSpacing: 1.2 },
  bookingActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  smallQrBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    backgroundColor: colors.accent, borderRadius: radius.pill,
    paddingHorizontal: 12, paddingVertical: 7,
  },
  smallQrBtnText: { fontFamily: fonts.sansBold, fontSize: 12, color: '#060606' },
  cancelBtn: {
    borderWidth: 1, borderColor: 'rgba(255,80,80,0.4)',
    borderRadius: radius.pill, paddingHorizontal: 12, paddingVertical: 7,
  },
  cancelBtnText: { fontFamily: fonts.sansMedium ?? fonts.sans, fontSize: 12, color: 'rgba(255,100,100,0.9)' },
  rescheduleBtn: {
    borderWidth: 1, borderColor: colors.accentBorder,
    borderRadius: radius.pill, paddingHorizontal: 12, paddingVertical: 7,
    backgroundColor: colors.accentSoft,
  },
  rescheduleBtnText: { fontFamily: fonts.sansBold, fontSize: 12, color: colors.accent },

  wellnessCard: {
    backgroundColor: colors.glass, borderRadius: radius.xl,
    borderWidth: 1, borderColor: colors.borderGlass, padding: 16,
  },
  wellnessCardTop: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 10 },
  wellnessServiceName: { fontFamily: fonts.sansBold, fontSize: 16, color: '#fff', marginBottom: 3 },
  wellnessPartnerName: { fontFamily: fonts.sans, fontSize: 12, color: colors.t2 },
  statusBadge: {
    borderRadius: radius.pill, paddingHorizontal: 10, paddingVertical: 4,
    borderWidth: 1, alignSelf: 'flex-start',
  },
  statusBadgeText: { fontFamily: fonts.sansBold, fontSize: 11 },
  wellnessMeta: { gap: 5, marginBottom: 12 },
  wellnessFooter: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
    borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 12,
  },
  wellnessAmount: { fontFamily: fonts.sansBold, fontSize: 18, color: '#fff' },
  wellnessActions: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  rateBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    backgroundColor: colors.accent, borderRadius: radius.pill,
    paddingHorizontal: 12, paddingVertical: 7,
  },
  rateBtnText: { fontFamily: fonts.sansBold, fontSize: 12, color: '#060606' },
  invoiceBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 5,
    borderWidth: 1, borderColor: colors.accentBorder, borderRadius: radius.pill,
    paddingHorizontal: 12, paddingVertical: 6,
  },
  invoiceBtnText: { fontFamily: fonts.sansBold, fontSize: 12, color: colors.accent },

  empty: { paddingTop: 80, alignItems: 'center', gap: 12 },
  emptyIcon: {
    width: 72, height: 72, borderRadius: 36,
    backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: colors.border,
    alignItems: 'center', justifyContent: 'center',
  },
  emptyTitle: { fontFamily: fonts.serif, fontSize: 22, color: '#fff' },
  emptySub: { fontFamily: fonts.sans, fontSize: 13, color: colors.t2, textAlign: 'center', maxWidth: 240, lineHeight: 20 },
  browseBtn: {
    backgroundColor: colors.accent, borderRadius: radius.pill,
    paddingHorizontal: 28, paddingVertical: 12, marginTop: 8,
  },
  browseBtnText: { fontFamily: fonts.sansBold, fontSize: 14, color: '#060606' },
});
