import { useState, useEffect, useCallback } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, RefreshControl } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors, fonts, radius } from '../theme/brand';
import { IconArrowLeft } from '../components/Icons';
import { api } from '../lib/api';

type BookingStatus = 'confirmed' | 'attended' | 'not_attended' | 'cancelled';

type Booking = {
  id: string;
  gymId?: string;
  slotDate: string;
  status: BookingStatus;
  bookingRef: string;
  bookedAt: string;
  isAutoGenerated?: boolean;
  slot?: { startTime: string; endTime: string; date: string };
  sessionType?: { name: string; color: string; kind: string };
  gym?: { name: string; id: string };
  subscription?: { planType?: string; startDate?: string; endDate?: string };
};

const FILTERS = ['All', 'Upcoming', 'Attended', 'Missed'] as const;
type Filter = typeof FILTERS[number];

const STATUS_CONFIG: Record<BookingStatus, { label: string; color: string }> = {
  confirmed: { label: 'Confirmed', color: '#00D46A' },
  attended: { label: 'Attended', color: '#00D4FF' },
  not_attended: { label: 'Not Attended', color: '#FFB400' },
  cancelled: { label: 'Cancelled', color: 'rgba(255,255,255,0.45)' },
};

function normalizeBookingStatus(value: any): BookingStatus {
  const status = String(value || 'confirmed').toLowerCase();
  if (status === 'attended') return 'attended';
  if (status === 'not_attended' || status === 'missed') return 'not_attended';
  if (status === 'cancelled' || status === 'canceled') return 'cancelled';
  return 'confirmed';
}

function todayISTValue() {
  return new Date(Date.now() + 5.5 * 3600 * 1000).toISOString().split('T')[0];
}

function dateValue(value: any) {
  return String(value || '').slice(0, 10);
}

function displayDate(value: any) {
  const raw = dateValue(value);
  if (!raw) return '-';
  const date = new Date(`${raw}T12:00:00Z`);
  if (!Number.isFinite(date.getTime())) return raw;
  return date.toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short' });
}

export default function MyBookings() {
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [filter, setFilter] = useState<Filter>('All');

  const load = useCallback(async (refresh = false) => {
    if (refresh) setRefreshing(true); else setLoading(true);
    try {
      const data: any = await api.get('/sessions/my-bookings');
      setBookings(Array.isArray(data) ? data : data?.bookings || data?.data || []);
    } catch {
      setBookings([]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const filtered = bookings.filter((booking) => {
    const status = normalizeBookingStatus(booking.status);
    if (filter === 'All') return true;
    if (filter === 'Upcoming') return status === 'confirmed';
    if (filter === 'Attended') return status === 'attended';
    if (filter === 'Missed') return status === 'not_attended';
    return true;
  });

  const cancelBooking = async (bookingId: string) => {
    try {
      await api.post(`/sessions/cancel/${bookingId}`, {});
      await load();
    } catch (e: any) {
      const { Alert } = require('react-native');
      Alert.alert('Error', e?.message || 'Could not cancel booking');
    }
  };

  const canRescheduleDayPass = (booking: Booking, status: BookingStatus) => {
    if (status !== 'cancelled' && status !== 'not_attended') return false;
    if (booking.subscription?.planType !== 'day_pass') return false;
    const validUntil = dateValue(booking.subscription?.endDate || booking.slotDate);
    return !!(booking.gym?.id || booking.gymId) && validUntil >= todayISTValue();
  };

  const rescheduleBooking = (booking: Booking) => {
    const targetGymId = booking.gym?.id || booking.gymId;
    if (!targetGymId) return;
    router.push({ pathname: '/slots', params: { gymId: targetGymId } } as any);
  };

  return (
    <SafeAreaView style={s.root}>
      <View style={s.header}>
        <TouchableOpacity style={s.back} onPress={() => router.back()}>
          <IconArrowLeft size={18} color="#fff" />
        </TouchableOpacity>
        <Text style={s.headerTitle}>My Bookings</Text>
        <View style={{ width: 38 }} />
      </View>

      <View style={s.filterRow}>
        {FILTERS.map((item) => (
          <TouchableOpacity
            key={item}
            style={[s.filterBtn, filter === item && s.filterBtnActive]}
            onPress={() => setFilter(item)}
          >
            <Text style={[s.filterText, filter === item && s.filterTextActive]}>{item}</Text>
          </TouchableOpacity>
        ))}
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={s.scroll}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.accent} />}
      >
        {loading ? (
          <View style={s.empty}><Text style={s.emptyText}>Loading bookings...</Text></View>
        ) : filtered.length === 0 ? (
          <View style={s.empty}>
            <Text style={s.emptyTitle}>No {filter !== 'All' ? `${filter.toLowerCase()} ` : ''}bookings</Text>
            <Text style={s.emptyText}>Browse gyms and book a session to get started.</Text>
            <TouchableOpacity style={s.exploreBtn} onPress={() => router.push('/(tabs)/explore' as any)}>
              <Text style={s.exploreBtnText}>Explore Gyms</Text>
            </TouchableOpacity>
          </View>
        ) : (
          filtered.map((booking) => {
            const status = normalizeBookingStatus(booking.status);
            const cfg = STATUS_CONFIG[status] || STATUS_CONFIG.confirmed;
            const gymName = booking.gym?.name || 'Gym';
            const sessionName = booking.sessionType?.name || 'Gym Workout';
            const sessionColor = booking.sessionType?.color || colors.accent;
            const date = displayDate(booking.slotDate);
            const time = booking.slot ? `${booking.slot.startTime} - ${booking.slot.endTime}` : '-';
            const canCancel = status === 'confirmed' && dateValue(booking.slotDate) >= todayISTValue();
            const canReschedule = canRescheduleDayPass(booking, status);

            return (
              <View key={booking.id} style={[s.card, { borderColor: `${sessionColor}22` }]}>
                <View style={s.cardTop}>
                  <View style={[s.typeDot, { backgroundColor: sessionColor }]} />
                  <Text style={[s.sessionName, { color: sessionColor }]} numberOfLines={1}>{sessionName}</Text>
                  {booking.isAutoGenerated && (
                    <View style={s.autoBadge}><Text style={s.autoBadgeText}>WALK-IN</Text></View>
                  )}
                  <View style={[s.statusBadge, { borderColor: `${cfg.color}44`, backgroundColor: `${cfg.color}15` }]}>
                    <Text style={[s.statusText, { color: cfg.color }]}>{cfg.label}</Text>
                  </View>
                </View>

                <Text style={s.gymName}>{gymName}</Text>

                <View style={s.infoRow}>
                  <Text style={s.infoItem}>Date: {date}</Text>
                  <Text style={s.infoItem}>Time: {time}</Text>
                  <Text style={[s.infoItem, s.bookingRef]}>#{booking.bookingRef || booking.id?.slice(0, 8)}</Text>
                </View>

                {(canCancel || canReschedule) && (
                  <View style={s.actionRow}>
                    {canCancel && (
                      <TouchableOpacity style={s.cancelBtn} onPress={() => cancelBooking(booking.id)}>
                        <Text style={s.cancelBtnText}>Cancel Booking</Text>
                      </TouchableOpacity>
                    )}
                    {canReschedule && (
                      <TouchableOpacity style={s.rescheduleBtn} onPress={() => rescheduleBooking(booking)}>
                        <Text style={s.rescheduleBtnText}>Choose New Time</Text>
                      </TouchableOpacity>
                    )}
                  </View>
                )}
              </View>
            );
          })
        )}
        <View style={{ height: 30 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 12,
  },
  back: {
    width: 38, height: 38, borderRadius: 12, backgroundColor: colors.surface,
    borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center',
  },
  headerTitle: { fontFamily: fonts.serif, fontSize: 20, color: '#fff' },
  filterRow: {
    flexDirection: 'row', gap: 8, paddingHorizontal: 20, marginBottom: 16,
  },
  filterBtn: {
    paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)',
  },
  filterBtnActive: { backgroundColor: colors.accentSoft, borderColor: colors.accentBorder },
  filterText: { fontFamily: fonts.sansBold, fontSize: 12, color: colors.t2 },
  filterTextActive: { color: colors.accent },
  scroll: { paddingHorizontal: 20 },
  card: {
    backgroundColor: 'rgba(255,255,255,0.04)', borderWidth: 1,
    borderRadius: radius.xl, padding: 16, marginBottom: 12,
  },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  typeDot: { width: 10, height: 10, borderRadius: 5 },
  sessionName: { fontFamily: fonts.sansBold, fontSize: 13, flex: 1 },
  autoBadge: {
    backgroundColor: 'rgba(255,220,0,0.12)', borderWidth: 1, borderColor: 'rgba(255,220,0,0.3)',
    borderRadius: 10, paddingHorizontal: 6, paddingVertical: 2,
  },
  autoBadgeText: { fontFamily: fonts.sansBold, fontSize: 8, color: '#FFD700', letterSpacing: 1 },
  statusBadge: {
    borderWidth: 1, borderRadius: 12, paddingHorizontal: 8, paddingVertical: 3,
  },
  statusText: { fontFamily: fonts.sansBold, fontSize: 10, letterSpacing: 0.5 },
  gymName: { fontFamily: fonts.serif, fontSize: 17, color: '#fff', marginBottom: 10 },
  infoRow: { flexDirection: 'row', gap: 14, flexWrap: 'wrap' },
  infoItem: { fontFamily: fonts.sans, fontSize: 12, color: colors.t2 },
  bookingRef: { color: colors.accent, fontFamily: fonts.sansBold, letterSpacing: 1.5 },
  actionRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 12, flexWrap: 'wrap' },
  cancelBtn: {
    flexGrow: 1, paddingVertical: 8, borderRadius: 20, alignItems: 'center',
    backgroundColor: 'rgba(255,107,107,0.08)', borderWidth: 1, borderColor: 'rgba(255,107,107,0.2)',
  },
  cancelBtnText: { fontFamily: fonts.sansBold, fontSize: 12, color: '#FF6B6B' },
  rescheduleBtn: {
    flexGrow: 1, paddingVertical: 8, borderRadius: 20, alignItems: 'center',
    backgroundColor: colors.accentSoft, borderWidth: 1, borderColor: colors.accentBorder,
  },
  rescheduleBtnText: { fontFamily: fonts.sansBold, fontSize: 12, color: colors.accent },
  empty: { alignItems: 'center', paddingTop: 80 },
  emptyTitle: { fontFamily: fonts.serif, fontSize: 22, color: '#fff', marginBottom: 8 },
  emptyText: { fontFamily: fonts.sans, fontSize: 14, color: colors.t2, textAlign: 'center', marginBottom: 24 },
  exploreBtn: {
    paddingHorizontal: 28, paddingVertical: 12, borderRadius: 24,
    backgroundColor: colors.accentSoft, borderWidth: 1, borderColor: colors.accentBorder,
  },
  exploreBtnText: { fontFamily: fonts.sansBold, fontSize: 14, color: colors.accent },
});
