import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Index } from 'typeorm';

export type BookingStatus = 'confirmed' | 'attended' | 'not_attended' | 'cancelled';

/**
 * A user's booking for a specific session slot.
 * Replaces the old slot_bookings table (schema is backward-compatible).
 */
@Entity('session_bookings')
@Index(['userId', 'gymId', 'slotDate'])
@Index(['slotId', 'userId'], { unique: true })
export class SessionBookingEntity {
  @PrimaryGeneratedColumn('uuid') id: string;

  @Column({ type: 'uuid' }) slotId: string;

  @Column({ type: 'uuid' }) userId: string;

  @Column({ type: 'uuid' }) gymId: string;

  @Column({ type: 'uuid', nullable: true }) subscriptionId: string;

  /** Denormalised for fast daily-limit queries */
  @Column({ length: 10 }) slotDate: string;

  /** confirmed | attended | not_attended | cancelled */
  @Column({ length: 20, default: 'confirmed' }) status: BookingStatus;

  @Column({ type: 'timestamp', nullable: true }) checkinAt: Date;

  /** True when auto-created during QR scan (walk-in with no prior booking) */
  @Column({ default: false }) isAutoGenerated: boolean;

  /** Short 6-char human-readable reference e.g. "YG3K2P" */
  @Column({ length: 8, nullable: true }) bookingRef: string;

  @CreateDateColumn() bookedAt: Date;
}
